### ISSUE TITLE
Please consider changing default behavior to print complete procyon output

### ISSUE THREAD

**Issue by shyiko** [Aivean/scala-to-java#1]
Current "[obfuscated output](https://github.com/Aivean/scala-to-java/blob/master/src/main/scala/com/github/scalatojava/Main.scala#L14)" mode should be enabled only if  some special command line option has been passed.

**Comment by Aivean** [comment]
You are welcome to create a pull request :)

**Comment by shyiko** [comment]
[#3](https://github.com/Aivean/scala-to-java/pull/3)
